// Curated emoji set with Vietnamese keywords for search.
// Keep the list focused on things used on a produce/farm/e-commerce site.

export type EmojiEntry = { e: string; vi: string[] };
export type EmojiGroup = { id: string; label: string; items: EmojiEntry[] };

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    id: 'food',
    label: 'Thực phẩm',
    items: [
      { e: '🥬', vi: ['rau', 'cải', 'xanh', 'lá'] },
      { e: '🥦', vi: ['bông cải', 'súp lơ', 'broccoli'] },
      { e: '🥕', vi: ['cà rốt', 'carrot', 'củ'] },
      { e: '🍅', vi: ['cà chua', 'tomato', 'đỏ'] },
      { e: '🥔', vi: ['khoai tây', 'potato', 'củ'] },
      { e: '🍆', vi: ['cà tím', 'eggplant'] },
      { e: '🌽', vi: ['bắp', 'ngô', 'corn'] },
      { e: '🌶️', vi: ['ớt', 'cay', 'chili'] },
      { e: '🫑', vi: ['ớt chuông', 'pepper', 'bell'] },
      { e: '🥒', vi: ['dưa chuột', 'dưa leo', 'cucumber'] },
      { e: '🧅', vi: ['hành', 'onion', 'củ'] },
      { e: '🧄', vi: ['tỏi', 'garlic'] },
      { e: '🥜', vi: ['đậu phộng', 'hạt', 'peanut', 'lạc'] },
      { e: '🫘', vi: ['đậu', 'bean', 'hạt'] },
      { e: '🌰', vi: ['hạt dẻ', 'chestnut'] },
      { e: '🥭', vi: ['xoài', 'mango'] },
      { e: '🍎', vi: ['táo', 'apple', 'đỏ'] },
      { e: '🍏', vi: ['táo xanh', 'apple green'] },
      { e: '🍐', vi: ['lê', 'pear'] },
      { e: '🍊', vi: ['cam', 'orange'] },
      { e: '🍋', vi: ['chanh', 'lemon', 'vàng'] },
      { e: '🍌', vi: ['chuối', 'banana'] },
      { e: '🍉', vi: ['dưa hấu', 'watermelon'] },
      { e: '🍇', vi: ['nho', 'grape'] },
      { e: '🍓', vi: ['dâu', 'strawberry', 'dâu tây'] },
      { e: '🫐', vi: ['việt quất', 'blueberry'] },
      { e: '🍒', vi: ['anh đào', 'cherry'] },
      { e: '🍑', vi: ['đào', 'peach'] },
      { e: '🍍', vi: ['dứa', 'thơm', 'khóm', 'pineapple'] },
      { e: '🥝', vi: ['kiwi'] },
      { e: '🥥', vi: ['dừa', 'coconut'] },
      { e: '🍄', vi: ['nấm', 'mushroom'] },
      { e: '🫒', vi: ['ô liu', 'olive'] },
      { e: '🥑', vi: ['bơ', 'avocado'] },
      { e: '🍞', vi: ['bánh mì', 'bread'] },
      { e: '🥐', vi: ['sừng bò', 'croissant', 'bánh'] },
      { e: '🥖', vi: ['bánh mì dài', 'baguette'] },
      { e: '🧀', vi: ['phô mai', 'cheese'] },
      { e: '🥚', vi: ['trứng', 'egg'] },
      { e: '🍳', vi: ['trứng ốp', 'chảo', 'cooking'] },
      { e: '🍚', vi: ['cơm', 'rice'] },
      { e: '🍜', vi: ['mì', 'phở', 'noodle'] },
      { e: '🍲', vi: ['canh', 'nồi', 'pot'] },
      { e: '🥣', vi: ['tô', 'bowl'] },
      { e: '🍱', vi: ['bento', 'cơm hộp'] },
      { e: '🍘', vi: ['bánh gạo', 'rice cracker'] },
      { e: '🍡', vi: ['bánh xiên'] },
      { e: '🍢', vi: ['xiên', 'oden'] },
      { e: '🍤', vi: ['tôm chiên', 'shrimp'] },
      { e: '🥩', vi: ['thịt', 'steak', 'bò'] },
      { e: '🍗', vi: ['gà', 'đùi gà', 'chicken'] },
      { e: '🍖', vi: ['thịt nướng', 'meat'] },
      { e: '🐟', vi: ['cá', 'fish'] },
      { e: '🦐', vi: ['tôm', 'shrimp'] },
      { e: '🦑', vi: ['mực', 'squid'] },
      { e: '🍯', vi: ['mật ong', 'honey'] },
      { e: '🥛', vi: ['sữa', 'milk'] },
      { e: '☕', vi: ['cà phê', 'coffee', 'trà'] },
      { e: '🍵', vi: ['trà', 'tea'] },
      { e: '🧃', vi: ['nước ép', 'juice', 'hộp'] },
      { e: '🧊', vi: ['đá', 'ice'] },
      { e: '🧂', vi: ['muối', 'salt'] },
    ],
  },
  {
    id: 'nature',
    label: 'Thiên nhiên',
    items: [
      { e: '🌱', vi: ['mầm', 'cây', 'sprout', 'nảy mầm'] },
      { e: '🌿', vi: ['lá', 'herb', 'thảo mộc'] },
      { e: '☘️', vi: ['cỏ ba lá', 'clover'] },
      { e: '🍀', vi: ['may mắn', 'cỏ bốn lá', 'clover'] },
      { e: '🌳', vi: ['cây', 'tree'] },
      { e: '🌲', vi: ['cây thông', 'pine'] },
      { e: '🌴', vi: ['cọ', 'palm'] },
      { e: '🪴', vi: ['chậu cây', 'plant'] },
      { e: '🌵', vi: ['xương rồng', 'cactus'] },
      { e: '🌾', vi: ['lúa', 'rice plant', 'cây lúa'] },
      { e: '🌸', vi: ['hoa anh đào', 'blossom'] },
      { e: '🌼', vi: ['hoa cúc', 'daisy'] },
      { e: '🌻', vi: ['hướng dương', 'sunflower'] },
      { e: '🌷', vi: ['tulip', 'hoa tulip'] },
      { e: '🌹', vi: ['hoa hồng', 'rose'] },
      { e: '💐', vi: ['bó hoa', 'bouquet'] },
      { e: '🌺', vi: ['dâm bụt', 'hibiscus'] },
      { e: '🌞', vi: ['mặt trời', 'sun'] },
      { e: '☀️', vi: ['nắng', 'sun', 'trời'] },
      { e: '⛅', vi: ['mây', 'cloud'] },
      { e: '☁️', vi: ['mây', 'cloud'] },
      { e: '🌧️', vi: ['mưa', 'rain'] },
      { e: '🌤️', vi: ['nắng mây', 'partly sunny'] },
      { e: '🌈', vi: ['cầu vồng', 'rainbow'] },
      { e: '💧', vi: ['giọt nước', 'drop', 'water'] },
      { e: '💦', vi: ['nước', 'sweat', 'splash'] },
      { e: '🔥', vi: ['lửa', 'fire'] },
      { e: '❄️', vi: ['tuyết', 'snow'] },
      { e: '🌍', vi: ['trái đất', 'earth'] },
    ],
  },
  {
    id: 'animals',
    label: 'Động vật',
    items: [
      { e: '🐄', vi: ['bò', 'cow'] },
      { e: '🐂', vi: ['trâu', 'bull'] },
      { e: '🐖', vi: ['heo', 'lợn', 'pig'] },
      { e: '🐓', vi: ['gà', 'rooster'] },
      { e: '🐣', vi: ['gà con', 'chick'] },
      { e: '🦆', vi: ['vịt', 'duck'] },
      { e: '🐑', vi: ['cừu', 'sheep'] },
      { e: '🐐', vi: ['dê', 'goat'] },
      { e: '🐰', vi: ['thỏ', 'rabbit'] },
      { e: '🐝', vi: ['ong', 'bee'] },
      { e: '🐞', vi: ['bọ rùa', 'ladybug'] },
      { e: '🦋', vi: ['bướm', 'butterfly'] },
      { e: '🐛', vi: ['sâu', 'worm'] },
      { e: '🦗', vi: ['dế', 'cricket'] },
      { e: '🐢', vi: ['rùa', 'turtle'] },
      { e: '🐠', vi: ['cá nhiệt đới', 'fish'] },
      { e: '🐕', vi: ['chó', 'dog'] },
      { e: '🐈', vi: ['mèo', 'cat'] },
    ],
  },
  {
    id: 'people',
    label: 'Con người',
    items: [
      { e: '👨‍🌾', vi: ['nông dân', 'farmer', 'nam'] },
      { e: '👩‍🌾', vi: ['nông dân nữ', 'farmer', 'nữ'] },
      { e: '👨‍🍳', vi: ['đầu bếp', 'chef', 'nam'] },
      { e: '👩‍🍳', vi: ['đầu bếp nữ', 'chef', 'nữ'] },
      { e: '👶', vi: ['em bé', 'baby'] },
      { e: '👧', vi: ['bé gái', 'girl'] },
      { e: '👦', vi: ['bé trai', 'boy'] },
      { e: '👩', vi: ['phụ nữ', 'woman'] },
      { e: '👨', vi: ['đàn ông', 'man'] },
      { e: '👪', vi: ['gia đình', 'family'] },
      { e: '🤱', vi: ['mẹ bế con', 'breastfeeding'] },
      { e: '🙌', vi: ['vỗ tay', 'hands up'] },
      { e: '🤝', vi: ['bắt tay', 'handshake'] },
      { e: '❤️', vi: ['trái tim', 'heart', 'yêu'] },
      { e: '💚', vi: ['tim xanh', 'green heart'] },
      { e: '💛', vi: ['tim vàng', 'yellow heart'] },
      { e: '✨', vi: ['lấp lánh', 'sparkle'] },
      { e: '👍', vi: ['đồng ý', 'thumbs up', 'like'] },
      { e: '✌️', vi: ['victory', 'v'] },
      { e: '🙏', vi: ['cảm ơn', 'praying', 'xin'] },
    ],
  },
  {
    id: 'commerce',
    label: 'Thương mại',
    items: [
      { e: '🛒', vi: ['giỏ hàng', 'cart', 'xe đẩy'] },
      { e: '🧺', vi: ['giỏ', 'basket'] },
      { e: '🛍️', vi: ['túi mua', 'shopping'] },
      { e: '📦', vi: ['hộp', 'package', 'đóng gói'] },
      { e: '🎁', vi: ['quà', 'gift'] },
      { e: '💰', vi: ['tiền', 'money', 'bao tiền'] },
      { e: '💵', vi: ['tiền mặt', 'cash'] },
      { e: '💳', vi: ['thẻ', 'card'] },
      { e: '🏦', vi: ['ngân hàng', 'bank'] },
      { e: '💸', vi: ['tiền bay', 'money fly'] },
      { e: '🧾', vi: ['hoá đơn', 'receipt'] },
      { e: '🏷️', vi: ['nhãn', 'label', 'tag'] },
      { e: '🔖', vi: ['bookmark', 'đánh dấu'] },
      { e: '📈', vi: ['tăng', 'chart up'] },
      { e: '📉', vi: ['giảm', 'chart down'] },
      { e: '📊', vi: ['biểu đồ', 'bar chart'] },
      { e: '🚚', vi: ['xe tải', 'delivery truck', 'giao'] },
      { e: '🛵', vi: ['xe máy', 'scooter', 'shipper'] },
      { e: '🏪', vi: ['tạp hoá', 'convenience store'] },
      { e: '🏬', vi: ['cửa hàng', 'store'] },
      { e: '🏠', vi: ['nhà', 'home', 'house'] },
    ],
  },
  {
    id: 'symbols',
    label: 'Ký hiệu',
    items: [
      { e: '✅', vi: ['tick', 'check', 'đúng'] },
      { e: '✔️', vi: ['check', 'ok'] },
      { e: '❌', vi: ['sai', 'wrong'] },
      { e: '⭐', vi: ['sao', 'star'] },
      { e: '🌟', vi: ['ngôi sao', 'glowing star'] },
      { e: '💯', vi: ['100', 'hundred'] },
      { e: '🎯', vi: ['mục tiêu', 'target'] },
      { e: '💡', vi: ['ý tưởng', 'idea', 'bóng đèn'] },
      { e: '🔔', vi: ['chuông', 'bell'] },
      { e: '⏰', vi: ['đồng hồ báo thức', 'alarm'] },
      { e: '⏱️', vi: ['đồng hồ bấm giờ', 'stopwatch'] },
      { e: '🕒', vi: ['đồng hồ', 'clock', 'giờ'] },
      { e: '📅', vi: ['lịch', 'calendar'] },
      { e: '📍', vi: ['ghim', 'pin', 'location'] },
      { e: '📞', vi: ['điện thoại', 'phone'] },
      { e: '📱', vi: ['smartphone', 'điện thoại'] },
      { e: '✉️', vi: ['thư', 'email', 'envelope'] },
      { e: '📨', vi: ['tin nhắn', 'incoming'] },
      { e: '📩', vi: ['email', 'envelope'] },
      { e: '❓', vi: ['hỏi', 'question'] },
      { e: '❗', vi: ['chấm than', 'exclamation'] },
      { e: '⚠️', vi: ['cảnh báo', 'warning'] },
      { e: '🚫', vi: ['cấm', 'prohibited'] },
      { e: '🔒', vi: ['khoá', 'lock'] },
      { e: '🔑', vi: ['chìa khoá', 'key'] },
      { e: '⚙️', vi: ['cài đặt', 'gear', 'settings'] },
      { e: '🔁', vi: ['lặp lại', 'repeat'] },
      { e: '♻️', vi: ['tái chế', 'recycle'] },
      { e: '🌐', vi: ['web', 'globe', 'internet'] },
      { e: '🏁', vi: ['cờ', 'checkered flag'] },
    ],
  },
];

export const ALL_EMOJIS: EmojiEntry[] = EMOJI_GROUPS.flatMap((g) => g.items);

export function normalizeVi(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .replace(/đ/g, 'd');
}

export function searchEmojis(q: string, items: EmojiEntry[] = ALL_EMOJIS): EmojiEntry[] {
  const needle = normalizeVi(q.trim());
  if (!needle) return items;
  return items.filter(
    (x) => x.e.includes(q) || x.vi.some((k) => normalizeVi(k).includes(needle)),
  );
}
